"""
Benchmark report generation for redbench.

Generates human-readable Markdown and console reports from evaluation results,
and structured JSON output for CI/CD integration.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any


class BenchmarkReporter:
    """
    Generates benchmark reports from BenchmarkEvaluator results.

    Supports three output formats:
      - Markdown: detailed report suitable for GitHub, papers, or READMEs.
      - Console: coloured terminal summary.
      - JSON: machine-readable output for CI/CD pipelines.

    Example:
        >>> evaluator = BenchmarkEvaluator()
        >>> results = evaluator.evaluate(my_tool)
        >>> reporter = BenchmarkReporter(tool_name="MyTool v1.0")
        >>> print(reporter.markdown(results))
        >>> reporter.save_json(results, "results.json")
    """

    def __init__(self, tool_name: str = "Unnamed Tool") -> None:
        """
        Initialise the reporter.

        Args:
            tool_name: Name of the tool being reported on.

        Raises:
            TypeError: If tool_name is not a string.
        """
        if not isinstance(tool_name, str):
            raise TypeError(f"tool_name must be str, got {type(tool_name).__name__}")
        self.tool_name = tool_name

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def markdown(self, results: dict[str, Any]) -> str:
        """
        Generate a Markdown benchmark report.

        Args:
            results: Return value from BenchmarkEvaluator.evaluate().

        Returns:
            Multi-section Markdown string.

        Raises:
            ValueError: If results is malformed.
        """
        self._validate_results(results)
        overall = results["overall"]
        per_class = results["per_class"]
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        lines: list[str] = [
            f"# redbench Evaluation Report: {self.tool_name}",
            f"",
            f"**Generated:** {ts}  ",
            f"**Samples evaluated:** {results['n_samples']}  ",
            f"**Correct predictions:** {results['n_correct']} / {results['n_samples']}",
            f"",
            "## Overall Metrics",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Precision | {overall['precision']:.4f} |",
            f"| Recall (TPR) | {overall['recall']:.4f} |",
            f"| F1 Score | **{overall['f1']:.4f}** |",
            f"| False Positive Rate | {overall['fpr']:.4f} |",
            f"| Accuracy | {overall['accuracy']:.4f} |",
            f"| True Positives | {overall['tp']} |",
            f"| False Positives | {overall['fp']} |",
            f"| True Negatives | {overall['tn']} |",
            f"| False Negatives | {overall['fn']} |",
            "",
            "## Per-Class Results",
            "",
            "| Class | Precision | Recall | F1 | FPR | TP | FP | TN | FN |",
            "|-------|-----------|--------|----|-----|----|----|----|----|",
        ]

        for vc, metrics in sorted(per_class.items()):
            lines.append(
                f"| {vc} | {metrics['precision']:.3f} | {metrics['recall']:.3f} | "
                f"**{metrics['f1']:.3f}** | {metrics['fpr']:.3f} | "
                f"{metrics['tp']} | {metrics['fp']} | {metrics['tn']} | {metrics['fn']} |"
            )

        # False negatives section (missed vulnerabilities — most interesting for research)
        fn_samples = [
            p for p in results.get("predictions", [])
            if p["true_label"] == "vulnerable" and p["predicted_label"] == "safe"
        ]
        if fn_samples:
            lines += [
                "",
                "## Missed Vulnerabilities (False Negatives)",
                "",
                f"The tool missed **{len(fn_samples)}** vulnerable samples:",
                "",
            ]
            for p in fn_samples[:20]:  # Cap at 20 to avoid extremely long reports
                lines.append(f"- `{p['sample_id']}` ({p['vuln_class']})")

        # False positives section
        fp_samples = [
            p for p in results.get("predictions", [])
            if p["true_label"] == "safe" and p["predicted_label"] == "vulnerable"
        ]
        if fp_samples:
            lines += [
                "",
                "## False Positives",
                "",
                f"The tool incorrectly flagged **{len(fp_samples)}** safe samples:",
                "",
            ]
            for p in fp_samples[:20]:
                lines.append(f"- `{p['sample_id']}` ({p['vuln_class']})")

        lines += ["", "---", f"*Generated by redbench v0.1.0*"]
        return "\n".join(lines)

    def console_summary(self, results: dict[str, Any]) -> str:
        """
        Generate a compact console-friendly summary.

        Args:
            results: Return value from BenchmarkEvaluator.evaluate().

        Returns:
            Multi-line string suitable for printing to a terminal.
        """
        self._validate_results(results)
        overall = results["overall"]
        sep = "=" * 60
        lines: list[str] = [
            sep,
            f"redbench Results: {self.tool_name}",
            sep,
            f"  Samples  : {results['n_samples']}  (correct: {results['n_correct']})",
            f"  F1       : {overall['f1']:.4f}",
            f"  Precision: {overall['precision']:.4f}",
            f"  Recall   : {overall['recall']:.4f}",
            f"  FPR      : {overall['fpr']:.4f}",
            f"  Accuracy : {overall['accuracy']:.4f}",
            "",
            "  Per-class F1:",
        ]
        for vc, metrics in sorted(results["per_class"].items()):
            bar_len = int(metrics["f1"] * 20)
            bar = "#" * bar_len + "." * (20 - bar_len)
            lines.append(
                f"    {vc:20s} [{bar}] {metrics['f1']:.3f}"
            )
        lines.append(sep)
        return "\n".join(lines)

    def to_json(self, results: dict[str, Any], indent: int = 2) -> str:
        """
        Serialise results to a JSON string.

        Args:
            results: Return value from BenchmarkEvaluator.evaluate().
            indent: JSON indentation level.

        Returns:
            JSON string.
        """
        self._validate_results(results)
        output = {
            "tool": self.tool_name,
            "timestamp": datetime.now(tz=timezone.utc).isoformat(),
            "overall": results["overall"],
            "per_class": results["per_class"],
            "n_samples": results["n_samples"],
            "n_correct": results["n_correct"],
        }
        return json.dumps(output, indent=indent)

    def save_json(self, results: dict[str, Any], output_path: str) -> None:
        """
        Save evaluation results to a JSON file.

        Args:
            results: Return value from BenchmarkEvaluator.evaluate().
            output_path: File path to write to.

        Raises:
            OSError: If the file cannot be written.
        """
        if not isinstance(output_path, str) or not output_path.strip():
            raise ValueError("output_path must be a non-empty string")
        json_str = self.to_json(results)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(json_str)

    def save_markdown(self, results: dict[str, Any], output_path: str) -> None:
        """
        Save the Markdown report to a file.

        Args:
            results: Return value from BenchmarkEvaluator.evaluate().
            output_path: File path to write to.

        Raises:
            OSError: If the file cannot be written.
        """
        if not isinstance(output_path, str) or not output_path.strip():
            raise ValueError("output_path must be a non-empty string")
        md = self.markdown(results)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(md)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _validate_results(self, results: dict[str, Any]) -> None:
        """Validate that results has the expected structure."""
        if not isinstance(results, dict):
            raise ValueError(f"results must be a dict, got {type(results).__name__}")
        required = {"overall", "per_class", "n_samples", "n_correct"}
        missing = required - set(results.keys())
        if missing:
            raise ValueError(
                f"results is missing required keys: {sorted(missing)}. "
                "Pass the return value of BenchmarkEvaluator.evaluate()."
            )
